# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/my_dev_db
test:
  <<: *default
  database: db/my_test_db

production:
  <<: *default
  database: db/my_prod_db
